definitions:
  domain.Account:
    properties:
      account_type:
        $ref: '#/definitions/domain.AccountType'
      create_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      update_at:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  domain.AccountType:
    enum:
    - admin
    type: string
    x-enum-varnames:
    - Admin
  domain.AppError:
    properties:
      code:
        type: integer
      messsage:
        type: string
    type: object
  domain.Category:
    properties:
      create_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/domain.Product'
        type: array
      update_at:
        type: string
    type: object
  domain.Product:
    properties:
      categories:
        items:
          $ref: '#/definitions/domain.Category'
        type: array
      create_at:
        type: string
      delete_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      update_at:
        type: string
    type: object
  domain.User:
    properties:
      account:
        $ref: '#/definitions/domain.Account'
      create_at:
        type: string
      delete_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      update_at:
        type: string
    type: object
  dto.AuthUserResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  dto.UpsertCategoryRequest:
    properties:
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Point Of Sale - Total Tools
  title: Point Of Sale API
  version: "1.0"
paths:
  /auth:
    post:
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthUserResponse'
      security:
      - BasicAuth: []
      tags:
      - Auth
  /categories:
    get:
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Category'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - Category
    post:
      parameters:
      - description: Category UpsertCategoryRequest
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.UpsertCategoryRequest'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Category'
      security:
      - ApiKeyAuth: []
      tags:
      - Category
  /categories/{id}:
    delete:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Category'
      security:
      - ApiKeyAuth: []
      tags:
      - Category
    get:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Category'
      security:
      - ApiKeyAuth: []
      tags:
      - Category
    put:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category UpsertCategoryRequest
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.UpsertCategoryRequest'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/domain.AppError'
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Category'
      security:
      - ApiKeyAuth: []
      tags:
      - Category
  /ping:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Ping
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
